services:
  rails:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ".:/var/source"
      - "./storage/bundle:/usr/local/bundle"
    environment:
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
      DATABASE_URL: "postgres://pgsql:password@pgsql:5432"
      SMTP_HOST: mailpit
      VITE_RUBY_HOST: "vite"
    depends_on:
      - pgsql

  pgsql:
    image: postgres:17
    entrypoint: ["/bin/bash", "-c", "if [ ${HOST_UID:-0} -gt 999 ] && [ ${HOST_GID:-0} -gt 999 ]; then groupmod -g ${HOST_GID:-0} postgres && usermod -g ${HOST_GID:-0} -u ${HOST_UID:-0} postgres; fi && /usr/local/bin/docker-entrypoint.sh postgres"]
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
      - ./docker/postgres_setup.sql:/docker-entrypoint-initdb.d/10-database-setup.sql
    environment:
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: password

  vite:
    build: .
    entrypoint: /var/source/bin/vite dev
    restart: unless-stopped
    ports:
      - 3036:3036
    volumes:
      - ".:/var/source"
      - "./storage/bundle:/usr/local/bundle"
    environment:
      VITE_RUBY_HOST: 0.0.0.0
    depends_on:
      - rails

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"

  image_processing:
    build: docker/image_processing
    ports:
      - "8080:8080"
    volumes:
      - "./docker/image_processing:/var/source"
      - "./tmp/snapshots:/var/snapshots"
