services:
  rails:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ".:/var/source"
      - "./storage/bundle:/usr/local/bundle"
    environment:
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
      DATABASE_URL: "postgres://pgsql:password@pgsql:5432"
      SMTP_HOST: mailpit
      VITE_RUBY_HOST: "vite"
    healthcheck:
      test: curl --fail http://localhost:3000/up
      start_interval: 2s
      start_period: 30s
    depends_on:
      - pgsql

  pgsql:
    image: postgres:17
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - pgsql-data:/var/lib/postgresql/data
      - ./docker/postgres_setup.sql:/docker-entrypoint-initdb.d/10-database-setup.sql:ro
    environment:
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      retries: 5
      start_period: 30s
      start_interval: 2s

  vite:
    build: .
    entrypoint: /var/source/bin/vite dev
    restart: unless-stopped
    ports:
      - 3036:3036
    volumes:
      - ".:/var/source"
      - "./storage/bundle:/usr/local/bundle"
    environment:
      VITE_RUBY_HOST: 0.0.0.0
    healthcheck:
      test: curl --fail http://localhost:3036
      start_interval: 2s
      start_period: 30s

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"

  image_processing:
    build: docker/image_processing
    ports:
      - "8080:8080"
    volumes:
      - "./docker/image_processing:/var/source"
      - "./tmp/snapshots:/var/snapshots"

volumes:
  pgsql-data:
